spring:
  application:
    name: etudiant-backend
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}

jwt:
  secret: c2FsdXQtbGF1cmVudC1jZWNpLWVzdC1tYS1zdXBlci1jbGUtc2VjcmV0ZS1wb3VyLWp3dC0yNTZiaXRz
  expiration: 86400000

logging:
  level:
    org:
      hibernate:
        type: info
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: info
    com:
      openclassrooms:
        etudiant: info

management:
  endpoints:
    web:
      exposure:
        include: '*'